
import streamlit as st
import pandas as pd
import joblib
import numpy as np
'''
# Load the trained model
@st.cache_resource
def load_model():
    return joblib.load("deployment_files/superkart_prediction_model_v1_0.joblib")

model = load_model()
'''
# Streamlit UI for Price Prediction
st.title("SuperKart Product Store Sales Prediction App")
st.write("This tool predicts the total revenue sales generated by a particular product from a particular store.")

st.subheader("Enter the product details:")

# Collect user input
Product_Weight = st.number_input("Product Weight" , min_value = 0.0,value = 10.0 , step = 0.01 ,format = "%.2f",help = "Enter the weight of the product in kg")
Product_Sugar_Content = st.selectbox("Product Sugar Content", ["Low Sugar", "Regular", "No Sugar","reg"])
Product_Allocated_Area = st.number_input("Product Allocated Area" , min_value = 0.0,max_value = 1.0,value = 0.2 , step = 0.001 ,format = "%.3f") 
Product_Type = st.selectbox("Product Type", ['Frozen Foods',
 'Dairy',
 'Canned',
 'Baking Goods',
 'Health and Hygiene',
 'Snack Foods',
 'Meat',
 'Household',
 'Hard Drinks',
 'Fruits and Vegetables',
 'Breads',
 'Soft Drinks',
 'Breakfast',
 'Others',
 'Starchy Foods',
 'Seafood'
 ]
  )
Product_MRP = st.number_input("Product MRP" , min_value = 0.0,  max_value = 500.00,value = 0.0 , step = 0.01 ,format = "%.2f") 
Store_Id = st.selectbox("Store Id",['OUT004', 'OUT003', 'OUT001', 'OUT002'] )
Store_Establishment_Year = st.selectbox("Store Establishment Year",[2009, 1999, 1987, 1998] )
Store_Size = st.selectbox("Store Size",['Medium', 'Small', 'High'] )
Store_Location_City_Type = st.selectbox("Store Location City Type",['Tier 1', 'Tier 2', 'Tier 3'] )
Store_Type = st.selectbox("Store Type",['Supermarket Type2', 'Departmental Store', 'Supermarket Type1', 'Food Mart'] )

# --------------------------------------------------# Create Input Payload# 

# Convert user input into a DataFrame
input_data = pd.DataFrame([{
    'Product_Weight': Product_Weight,
    'Product_Sugar_Content': Product_Sugar_Content,
    'Product_Allocated_Area': Product_Allocated_Area,
    'Product_Type': Product_Type,
    'Product_MRP': Product_MRP,
    'Store_Id': Store_Id,
    'Store_Establishment_Year': Store_Establishment_Year,
    'Store_Size': Store_Size,
    'Store_Location_City_Type': Store_Location_City_Type,
    'Store_Type' : Store_Type
}])

# --------------------------------------------------
# Prediction
# --------------------------------------------------

if st.button("Predict Sales Revenue"):

    try:

        API_URL = "http://127.0.0.1:5000/predict"

        response = requests.post(
            API_URL,
            json=payload
        )

        if response.status_code == 200:

            prediction = response.json()[
                "predicted_product_store_sales"
            ]

            st.success(
                f"Predicted Product Store Sales: ₹ {prediction:,.2f}"
            )

        else:

            st.error(
                f"API Error: {response.text}"
            )

    except Exception as e:

        st.error(
            f"Could not connect to Flask API. Error: {str(e)}"
        

